// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk2ul6RXpD_hpXZHRJghUejo6_upKrWa4',
    appId: '1:975760039249:web:5746f0102815ac274bc770',
    messagingSenderId: '975760039249',
    projectId: 'ortog-citas',
    authDomain: 'ortog-citas.firebaseapp.com',
    storageBucket: 'ortog-citas.appspot.com',
    measurementId: 'G-LTKLFK3LVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYc2jkdMcMqL_iWrJpms6jwjSMoCTzynE',
    appId: '1:975760039249:android:7ccacb8ebaff73f14bc770',
    messagingSenderId: '975760039249',
    projectId: 'ortog-citas',
    storageBucket: 'ortog-citas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgNBEZ1IQH8W4ka_rtFwG6nxrC5OxWxw',
    appId: '1:975760039249:ios:eec50b64e2bc255a4bc770',
    messagingSenderId: '975760039249',
    projectId: 'ortog-citas',
    storageBucket: 'ortog-citas.appspot.com',
    iosBundleId: 'com.example.ortogCitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjgNBEZ1IQH8W4ka_rtFwG6nxrC5OxWxw',
    appId: '1:975760039249:ios:eec50b64e2bc255a4bc770',
    messagingSenderId: '975760039249',
    projectId: 'ortog-citas',
    storageBucket: 'ortog-citas.appspot.com',
    iosBundleId: 'com.example.ortogCitas',
  );
}
